<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use App\Models\Channel;

class ChannelsSeeder extends Seeder
{
    public function run(): void
    {
        $sourcePath = database_path('seeders/assets/channels');
        $destinationPath = 'channels';

        if (!Storage::disk('public')->exists($destinationPath)) {
            Storage::disk('public')->makeDirectory($destinationPath);
        }

        $channels = [
            [
                'image_url' => 'channels/101-AztecaUNO.png',
                'number' => 101,
                'origin' => 'KU 07',
                'name' => 'Azteca UNO',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/102-182-LasEstrellas.png',
                'number' => 102,
                'origin' => 'KU 07',
                'name' => 'Las Estrellas',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/103-ImagenTV.png',
                'number' => 103,
                'origin' => 'KU 07',
                'name' => 'Imagen TV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/105-Canal5.png',
                'number' => 105,
                'origin' => 'KU 07',
                'name' => 'Canal 5',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/107-Azteca7.png',
                'number' => 107,
                'origin' => 'KU 07',
                'name' => 'Azteca 7',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/111-OnceTV.png',
                'number' => 111,
                'origin' => 'KU 05',
                'name' => 'Once TV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/114-Catorce.png',
                'number' => 114,
                'origin' => 'KU 05',
                'name' => 'Catorce',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/120-TVUNAM.png',
                'number' => 120,
                'origin' => 'KU 05',
                'name' => 'TV UNAM',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/122-Canal22.png',
                'number' => 122,
                'origin' => 'KU 09',
                'name' => 'Canal 22',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/145-Congreso.png',
                'number' => 145,
                'origin' => 'KU 07',
                'name' => 'Congreso',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/149-LaMexicana.png',
                'number' => 149,
                'origin' => 'KU 01',
                'name' => 'La Mexicana',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/151-MTV.png',
                'number' => 151,
                'origin' => 'KU 13',
                'name' => 'MTV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/152-Teleritmo.png',
                'number' => 152,
                'origin' => 'KU 07',
                'name' => 'Teleritmo',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/153-TelehitMusica.png',
                'number' => 153,
                'origin' => 'KU 13',
                'name' => 'Telehit Musica',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/154-Telehit.png',
                'number' => 154,
                'origin' => 'KU 05',
                'name' => 'Telehit',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/155-Bandamax.png',
                'number' => 155,
                'origin' => 'KU 13',
                'name' => 'Bandamax',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/156-LaMejorTV.png',
                'number' => 156,
                'origin' => 'KU 09',
                'name' => 'La Mejor TV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/157-EXATV.png',
                'number' => 157,
                'origin' => 'KU 09',
                'name' => 'EXA TV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/158-UltraBanda.png',
                'number' => 158,
                'origin' => 'KU 07',
                'name' => 'Ultra Banda',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/159-MTV00s.png',
                'number' => 159,
                'origin' => 'KU 09',
                'name' => 'MTV 00s',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/102-182-LasEstrellas.png',
                'number' => 182,
                'origin' => 'KU 09',
                'name' => 'Las Estrellas -2 Hrs',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/186-ForoTV.png',
                'number' => 186,
                'origin' => 'KU 05',
                'name' => 'Foro TV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/187-TVOAI.png',
                'number' => 187,
                'origin' => 'OVERON',
                'name' => 'TVOAI',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/188-Teleformula.png',
                'number' => 188,
                'origin' => 'KU 09',
                'name' => 'Teleformula',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/189-Nueve.png',
                'number' => 189,
                'origin' => 'KU 13',
                'name' => 'Nueve',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/190-Agrotendencia.png',
                'number' => 190,
                'origin' => 'KU 07',
                'name' => 'Agrotendencia',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/200-StarLink.png',
                'number' => 200,
                'origin' => 'KU 01',
                'name' => 'StarLink',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            // Here
            [
                'image_url' => 'channels/400-UltraClásico.png',
                'number' => 400,
                'origin' => 'OVERON',
                'name' => 'Ultra Clásico',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/401-DePelicula.png',
                'number' => 401,
                'origin' => 'KU 13',
                'name' => 'De Película',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/402-Cinelatino.png',
                'number' => 402,
                'origin' => 'KU 09',
                'name' => 'Cinelatino',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/403-Paramount.png',
                'number' => 403,
                'origin' => 'KU 13',
                'name' => 'Paramount',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/407-Golden.png',
                'number' => 407,
                'origin' => 'KU 13',
                'name' => 'Golden',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/408-GoldenEdge.png',
                'number' => 408,
                'origin' => 'KU 13',
                'name' => 'Golden Edge',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/411-Cinecanal.png',
                'number' => 411,
                'origin' => 'KU 05',
                'name' => 'Cinecanal',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/412-StudioUniversal.png',
                'number' => 412,
                'origin' => 'KU 05',
                'name' => 'Studio Universal',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/414-SonyMovies.png',
                'number' => 414,
                'origin' => 'KU 09',
                'name' => 'Sony Movies',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/415-TNT.png',
                'number' => 415,
                'origin' => 'KU 05',
                'name' => 'TNT',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/417-Cinemax.png',
                'number' => 417,
                'origin' => 'KU 01',
                'name' => 'Cinemax',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/418-Space.png',
                'number' => 418,
                'origin' => 'KU 01',
                'name' => 'Space',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/420-PopCornCentral.png',
                'number' => 420,
                'origin' => 'KU 09',
                'name' => 'PopCorn Central',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/421-Cinema.png',
                'number' => 421,
                'origin' => 'KU 05',
                'name' => 'Cinema',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/430-AdultSwim.png',
                'number' => 430,
                'origin' => 'KU 09',
                'name' => 'Adult Swim',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/451-HBO.png',
                'number' => 451,
                'origin' => 'KU 01',
                'name' => 'HBO',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/452-HBO2.png',
                'number' => 452,
                'origin' => 'KU 13',
                'name' => 'HBO 2',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/453-HBOMUNDI.png',
                'number' => 453,
                'origin' => 'KU 13',
                'name' => 'HBO MUNDI',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/454-HBOFAMILY.png',
                'number' => 454,
                'origin' => 'KU 13',
                'name' => 'HBO FAMILY',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/455-HBOXTREME.png',
                'number' => 455,
                'origin' => 'KU 13',
                'name' => 'HBO XTREME',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/457-HBOPOP.png',
                'number' => 457,
                'origin' => 'KU 13',
                'name' => 'HBO POP',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/461-UniversalPremiere.png',
                'number' => 461,
                'origin' => 'KU 09',
                'name' => 'Universal Premiere',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/462-UniversalCinema.png',
                'number' => 462,
                'origin' => 'KU 09',
                'name' => 'Universal Cinema',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/463-UniversalComedy.png',
                'number' => 463,
                'origin' => 'KU 09',
                'name' => 'Universal Comedy',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/464-UniversalCrime.png',
                'number' => 464,
                'origin' => 'KU 09',
                'name' => 'Universal Crime',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/465-UniversalReality.png',
                'number' => 465,
                'origin' => 'KU 09',
                'name' => 'Universal Reality',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/501-ESPN.png',
                'number' => 501,
                'origin' => 'KU 01',
                'name' => 'ESPN',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/502-ESPN2.png',
                'number' => 502,
                'origin' => 'KU 13',
                'name' => 'ESPN 2',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/503-ESPN3.png',
                'number' => 503,
                'origin' => 'KU 01',
                'name' => 'ESPN 3',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/504-ESPN4.png',
                'number' => 504,
                'origin' => 'KU 01',
                'name' => 'ESPN 4',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/505-FOXSports.png',
                'number' => 505,
                'origin' => 'KU 01',
                'name' => 'FOX Sports',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/506-FOXSports2.png',
                'number' => 506,
                'origin' => 'KU 05',
                'name' => 'FOX Sports 2',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/507-FOXSports3.png',
                'number' => 507,
                'origin' => 'KU 05',
                'name' => 'FOX Sports 3',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/508-FOXSportsPremium.png',
                'number' => 508,
                'origin' => 'KU 01',
                'name' => 'FOX Sports Premium',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/509-Adrenalina.png',
                'number' => 509,
                'origin' => 'KU 01',
                'name' => 'Adrenalina Sports Network',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/510-TUDN.png',
                'number' => 510,
                'origin' => 'KU 13',
                'name' => 'TUDN',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/511-TVAztecaDeportes.png',
                'number' => 511,
                'origin' => 'KU 07',
                'name' => 'TV Azteca Deportes',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/515-ClaroSports.png',
                'number' => 515,
                'origin' => 'KU 07',
                'name' => 'Claro Sports',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/518-DiscoveryTurbo.png',
                'number' => 518,
                'origin' => 'KU 07',
                'name' => 'Discovery Turbo',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/520-CalienteTV.png',
                'number' => 520,
                'origin' => 'KU 07',
                'name' => 'Caliente TV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/602-CNNESPAÑOL.png',
                'number' => 602,
                'origin' => 'KU 13',
                'name' => 'CNN en Español',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/603-Milenio.png',
                'number' => 603,
                'origin' => 'KU 01',
                'name' => 'Milenio',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/604-ElFinanciero.png',
                'number' => 604,
                'origin' => 'KU 07',
                'name' => 'El Financiero',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'RESTART/CUTV',
                'status' => true,
            ],
            [
                'image_url' => 'channels/605-CNN.png',
                'number' => 605,
                'origin' => 'KU 05',
                'name' => 'CNN',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/606-ElHeraldo.png',
                'number' => 606,
                'origin' => 'KU 01',
                'name' => 'El Heraldo',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/607-JusticiaTV.png',
                'number' => 607,
                'origin' => 'KU 09',
                'name' => 'Justicia TV',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/608-AMÁS+.png',
                'number' => 608,
                'origin' => 'OVERON',
                'name' => 'AMÁS+',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/609-ADN40.png',
                'number' => 609,
                'origin' => 'KU 07',
                'name' => 'ADN 40',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/631-Playboy.png',
                'number' => 631,
                'origin' => 'KU 05',
                'name' => 'Playboy',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/632-Venus.png',
                'number' => 632,
                'origin' => 'KU 05',
                'name' => 'Venus',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/644-646-RadioCañón.png',
                'number' => 644,
                'origin' => 'KU 05',
                'name' => 'Radio Cañón Zacatecas',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/644-646-RadioCañón.png',
                'number' => 646,
                'origin' => 'KU 05',
                'name' => 'Radio Cañón Guadalajara',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 701,
                'origin' => 'KU 09',
                'name' => 'Stingray Pop Latino Actual',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 702,
                'origin' => 'KU 09',
                'name' => 'Stingray Éxitos Tropicales',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 703,
                'origin' => 'KU 09',
                'name' => 'Stingray Rock En Español',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 704,
                'origin' => 'KU 09',
                'name' => 'Stingray Mariachi Para Siempre',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 705,
                'origin' => 'KU 09',
                'name' => 'Stingray Viva México',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 706,
                'origin' => 'KU 09',
                'name' => 'Stingray Reggaeton',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 707,
                'origin' => 'KU 09',
                'name' => 'Stingray Romance Latino',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 708,
                'origin' => 'KU 09',
                'name' => 'Stingray Salsa Y Merengue',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 709,
                'origin' => 'KU 09',
                'name' => 'Stingray Latin Lounge',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 710,
                'origin' => 'KU 09',
                'name' => 'Stingray Viejitas Pero Buenísimas',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 711,
                'origin' => 'KU 09',
                'name' => 'Stingray Hard Rock',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 712,
                'origin' => 'KU 09',
                'name' => 'Stingray Rock Alternativo',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 713,
                'origin' => 'KU 09',
                'name' => 'Stingray Clásicos Indie',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 714,
                'origin' => 'KU 09',
                'name' => 'Stingray Años 80',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 715,
                'origin' => 'KU 09',
                'name' => 'Stingray Años 90',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 716,
                'origin' => 'KU 09',
                'name' => 'Stingray Éxitos Recientes',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 717,
                'origin' => 'KU 09',
                'name' => 'Stingray Pop Adulto',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 718,
                'origin' => 'KU 09',
                'name' => 'Stingray Solo Para Peques',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 719,
                'origin' => 'KU 09',
                'name' => 'Stingray Jazz Latino',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 720,
                'origin' => 'KU 09',
                'name' => 'Stingray Maestros del Jazz',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 721,
                'origin' => 'KU 09',
                'name' => 'Stingray Cocktail Lounge',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 722,
                'origin' => 'KU 09',
                'name' => 'Stingray El Salón Chill',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 723,
                'origin' => 'KU 09',
                'name' => 'Stingray Ópera Plus',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 724,
                'origin' => 'KU 09',
                'name' => 'Stingray Clásicos Para Todos',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/701-725-StingrayMusic.png',
                'number' => 725,
                'origin' => 'KU 09',
                'name' => 'Stingray Eventos Especiales',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Stingray Music',
                'status' => true,
            ],
            [
                'image_url' => 'channels/726-LaKeBuena.png',
                'number' => 726,
                'origin' => 'KU 11',
                'name' => 'La Ke Buena',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
            [
                'image_url' => 'channels/727-Los40.png',
                'number' => 727,
                'origin' => 'KU 11',
                'name' => 'Los 40',
                'url' => 'https://www.youtube.com/watch?v=GYeADDB0Rt8',
                'category' => 'Standard TV Channel',
                'status' => true,
            ],
        ];

        foreach ($channels as $channel) {
            $filename = basename($channel['image_url']);
            $sourceFile = $sourcePath . '/' . $filename;

            if (!File::exists($sourceFile)) {
                $this->command->warn("Image not found: $filename — This channel will be skipped.");
                continue;
            }

            Storage::disk('public')->putFileAs($destinationPath, new \Illuminate\Http\File($sourceFile), $filename);

            Channel::create([
                ...$channel,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('Channels inserted correctly.');
    }
}
